# Site settings
author: Saudia Schwegler
title: My Personal Introduction
header-img: img/home-bg.png
email: saudiaschwegler@gmail.com
copyright_name: Saudia Schwegler
description: > # this means to ignore newlines until "baseurl:"
  About Me
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ssaudia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
